### ISSUE TITLE
Registry Image pst418/distribution:pr

### ISSUE THREAD

**Issue by FaKod** [exoscale/multi-master-kubernetes#36]
Du you have a Dockerfile for that image?

**Comment by pst** [comment]
The Dockerfile is unchanged from upstream, but this image already includes our patch to make the v2 signing work against SOS. You can find the PR here with all the details. Unfortunately it seems to be low priority for Docker to get this merged.

https://github.com/docker/distribution/pull/2069

**Comment by FaKod** [comment]
The reason for my question:
You are using a Image from an unknown user (pst418) and unknown source (distribution).
So I would like to have more information of what I am deploying...

**Comment by greut** [comment]
doing some github issue gardening... :)
