### ISSUE TITLE
creating 2 additional workers usually fails

### ISSUE THREAD

**Issue by FaKod** [exoscale/multi-master-kubernetes#37]
TASK [defunctzombie.coreos-bootstrap : Check if bootstrap is needed] ***********
changed: [xx-worker-0d7c109]
changed: [xx-worker-0a066ad]
changed: [xx-worker-aa9cc92]
fatal: [x-worker-9a3fb7d]: FAILED! => {"changed": true, "failed": true, "rc": 1, "stderr": "Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\nShared connection to x.x.x.x closed.\r\n", "stdout": "stat: cannot stat '/home/core/.bootstrapped': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/.bootstrapped': No such file or directory"]}
...ignoring
fatal: [xx-worker-7055b96]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host y.y.y.y port 22: Connection timed out\r\n", "unreachable": true}

**Comment by pst** [comment]
Thanks for the report, to better understand the error, are you running Ansible on your local machine? You say usually fails, does that mean it sometimes works?

After running the worker-add playbook, have you tried running the cluster-bootstrap playbook? Does the connection to the worker that had the connection error before work then?

**Comment by FaKod** [comment]
I ran Ansible in your Docker Container
It worked only once (first time). Tried it around 20 times.
If I enter the hosts to inventory manually (if they are missing), cluster-bootstrap playbook works

**Comment by pst** [comment]
Thanks for the feedback. I can confirm this issue but am not sure yet what causes it yet. I've had this before, but thought it was fixed after I added the code that manually adds all nodes to the inventory during the run. I will investigate today.

**Comment by llambiel** [comment]
This repository has been deprecated and is no longer maintained
