### ISSUE TITLE
AnsibleUndefinedVariable while adding one node with worker-add.yml

### ISSUE THREAD

**Issue by FaKod** [exoscale/multi-master-kubernetes#40]
TASK [infra-inventory : write inventory file] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'master_eip' is undefined"}
	to retry, use: --limit @/playbook/worker-add.retry

**Comment by llambiel** [comment]
This repository has been deprecated and is no longer maintained
