### ISSUE TITLE
Can't create working Kubernetes Cluster

### ISSUE THREAD

**Issue by bn4t** [exoscale/multi-master-kubernetes#49]
I'm trying to create a Kubernetes Cluster using this ansible script.
Unfortunately I fail with one of the following scenarios:

1. Ansible script successfully sets up nodes but can't connect to worker nodes over SSH. After retrying with `ansible-playbook cluster-bootstrap.yml  --limit @/playbook/cluster-bootstrap.retry` the worker nodes are reachable over SSH. When I now try to interact with `kubectl` following error appears:
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`

2. The Ansible script runs fine until the `addons : wait_for` task. After waiting 30 minutes it says that it couldn't connect to localhost.

I'm not sure if I'm doing something wrong.
Between the tries I always deleted all firewall security groups, flexible ips, and ssh keys which were created by the script.

**Comment by greut** [comment]
Hi @Apply55gx, I'm sorry to confirm your issue.
